name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        
      - run: pip install mkdocs-material
      - run: pip install mkdocs-exclude
      - run: pip install mkdocs-roamlinks-plugin

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOmaster: mkdocs.i-kubernetes.com
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base